%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "16.36"
   CudaEnabledDeviceCount: -1
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "5.1"
   Duration_MS_Min: "0.1"
   Duration_MS_Max: "84.3"
   Duration_MS_Last: "0.2"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "J:EMCAStitchingrid_1_1"
CapturePostProcessing:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "2.0"
   Duration_MS_Min: "1.6"
   Duration_MS_Max: "7.9"
   Duration_MS_Last: "2.2"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   downsample_preview_factor: 4
Matcher:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 1
   Duration_MS_Mean: "1.0"
   Duration_MS_Min: "0.8"
   Duration_MS_Max: "3.7"
   Duration_MS_Last: "1.0"
   template_sizeX: 256
   template_sizeY: 256
   hessian_threshold: 400
   units_per_pixel: 1.
   units: nM
Simple:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.2"
   Duration_MS_Min: "0.1"
   Duration_MS_Max: "1.8"
   Duration_MS_Last: "0.2"
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "4.3"
   Duration_MS_Min: "3.3"
   Duration_MS_Max: "15.0"
   Duration_MS_Last: "3.9"
   use_Cuda: 0
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "23.7"
   Duration_MS_Min: "21.1"
   Duration_MS_Max: "68.1"
   Duration_MS_Last: "24.3"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 256
   omega: 50
Canny1:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "1.9"
   Duration_MS_Min: "1.3"
   Duration_MS_Max: "5.7"
   Duration_MS_Last: "2.0"
   threshold1: 100
   threshold2: 200
Canny2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Cartoon1:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   algorithm: 1
   r: 352
   s: 408
Cartoon2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   algorithm: 2
   r: 375
   s: 465
