%YAML:1.0
GraphManager:
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "3.1"
   Duration_MS_Min: "0.4"
   Duration_MS_Max: "3312.3"
   Duration_MS_Last: "0.5"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: ""
Cartoon:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "27.1"
   Duration_MS_Min: "26.0"
   Duration_MS_Max: "46.5"
   Duration_MS_Last: "27.5"
