%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "11.02"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "11.0"
   Duration_MS_Min: "0.8"
   Duration_MS_Max: "639.3"
   Duration_MS_Last: "1.0"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "J:EMCAStitchingrid_1_1"
Simple:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "1.9"
   Duration_MS_Min: "1.6"
   Duration_MS_Max: "3.7"
   Duration_MS_Last: "1.9"
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "4.6"
   Duration_MS_Min: "4.1"
   Duration_MS_Max: "10.0"
   Duration_MS_Last: "4.2"
   use_Cuda: 0
Canny1:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Canny2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Cartoon1:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "26.8"
   Duration_MS_Min: "26.1"
   Duration_MS_Max: "29.1"
   Duration_MS_Last: "26.5"
   algorithm: 1
   r: 352
   s: 408
Cartoon2:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "26.3"
   Duration_MS_Min: "25.6"
   Duration_MS_Max: "27.2"
   Duration_MS_Last: "26.7"
   algorithm: 2
   r: 375
   s: 465
