%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: 3.7705589496917642e+000
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 0
CamXimea:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "226.1"
   Duration_MS_Min: "225.3"
   Duration_MS_Max: "230.9"
   Duration_MS_Last: "225.5"
   camera_index: 0
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 100000
   exposureSliderMax: 10000
   gain: 0
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 1
Average:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   frames_to_average: 4
BrightDark:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 7
FocusFFT:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 8
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 1024
   omega: 43
FocusLaplace:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 3
Canny:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 65
   threshold2: 96
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "39.0"
   Duration_MS_Min: "35.0"
   Duration_MS_Max: "168.8"
   Duration_MS_Last: "36.4"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
   writeCaptureStream: 1
