%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 0
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "124.5"
   Duration_MS_Min: "116.3"
   Duration_MS_Max: "583.7"
   Duration_MS_Last: "118.7"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 5070
   gain: 423
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "15.4"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "41.3"
   Duration_MS_Last: "15.1"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 0
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 3
   show_slider: 1
