%YAML:1.0
GraphManager:
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "111.5"
   Duration_MS_Min: "107.9"
   Duration_MS_Max: "135.4"
   Duration_MS_Last: "108.0"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 4183
   exposureSliderMax: 15000
   gain: 479
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
BrightDark:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "12.7"
   Duration_MS_Min: "12.2"
   Duration_MS_Max: "14.7"
   Duration_MS_Last: "12.3"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.4"
   Duration_MS_Min: "13.0"
   Duration_MS_Max: "38.9"
   Duration_MS_Last: "13.4"
   use_Cuda: 1
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "61.2"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "889.1"
   Duration_MS_Last: "0.0"
   directory: "J:/junk"
   name: foo
   ext: ".tif"
   # Set writeOnKeyHit to a single char to trigger write if that key is hit
   writeOnKeyHit: g
