%YAML:1.0
GraphManager:
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "119.1"
   Duration_MS_Min: "107.4"
   Duration_MS_Max: "580.8"
   Duration_MS_Last: "113.1"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 19155
   gain: 648
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "15.4"
   Duration_MS_Min: "14.6"
   Duration_MS_Max: "38.8"
   Duration_MS_Last: "14.8"
   use_Cuda: 1
Canny:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "54.8"
   Duration_MS_Min: "53.3"
   Duration_MS_Max: "66.3"
   Duration_MS_Last: "54.1"
