%YAML:1.0
GraphManager:
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "110.6"
   Duration_MS_Min: "106.9"
   Duration_MS_Max: "162.7"
   Duration_MS_Last: "110.3"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 4507
   gain: 3352
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Average:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.6"
   Duration_MS_Min: "2.1"
   Duration_MS_Max: "6.7"
   Duration_MS_Last: "4.2"
   frames_to_average: 4
   show_slider: 1
BrightDark:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.8"
   Duration_MS_Min: "11.0"
   Duration_MS_Max: "14.2"
   Duration_MS_Last: "11.1"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "3.4"
   Duration_MS_Min: "13.1"
   Duration_MS_Max: "41.0"
   Duration_MS_Last: "13.2"
   use_Cuda: 1
