%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.7"
   Duration_MS_Min: "0.5"
   Duration_MS_Max: "0.8"
   Duration_MS_Last: "0.7"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: ""
Cartoon:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "6295.2"
   Duration_MS_Min: "6217.9"
   Duration_MS_Max: "6441.2"
   Duration_MS_Last: "6226.6"
