%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
CamXimea:
   IsEnabled: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "122.8"
   Duration_MS_Min: "118.1"
   Duration_MS_Max: "588.7"
   Duration_MS_Last: "122.7"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 3380
   gain: 4958
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
Stats:
   IsEnabled: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "15.1"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "41.9"
   Duration_MS_Last: "15.2"
   use_Cuda: 1
