%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "3.09"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "50.0"
   Duration_MS_Min: "44.4"
   Duration_MS_Max: "66.6"
   Duration_MS_Last: "48.2"
   camera_index: 0
   trigger_software: 1
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 5268
   exposureSliderMax: 10000
   gain: 0
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 1
CapturePostProcessing:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "64.4"
   Duration_MS_Min: "63.7"
   Duration_MS_Max: "75.9"
   Duration_MS_Last: "64.1"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   downsample_preview_factor: 2
QC:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "10.8"
   Duration_MS_Min: "9.0"
   Duration_MS_Max: "14.3"
   Duration_MS_Last: "9.2"
Stats:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   use_Cuda: 1
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 8
   InputStream: 0
   Duration_MS_Mean: "51.4"
   Duration_MS_Min: "45.3"
   Duration_MS_Max: "384.7"
   Duration_MS_Last: "51.3"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 1024
   omega: 481
FocusSobel:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 3
FocusLaplace:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 3
Canny:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 65
   threshold2: 96
Simple:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 1
   Duration_MS_Mean: "78.5"
   Duration_MS_Min: "72.8"
   Duration_MS_Max: "161.2"
   Duration_MS_Last: "76.6"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
