%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.2"
   Duration_MS_Last: "0.0"
   # Set camera_index to -1 to skip use of camera
   camera_index: -1
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "C:/Smart16/Grid_2_SMART/"
