%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "142.8"
   Duration_MS_Min: "136.8"
   Duration_MS_Max: "598.2"
   Duration_MS_Last: "140.8"
   camera_index: 0
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 4002
   exposureSliderMax: 10000
   gain: 288
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
Average:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   frames_to_average: 4
BrightDark:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.0"
   Duration_MS_Min: "13.1"
   Duration_MS_Max: "87.4"
   Duration_MS_Last: "13.6"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "19.0"
   Duration_MS_Min: "16.9"
   Duration_MS_Max: "43.5"
   Duration_MS_Last: "18.5"
   kernel_size: 7
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 8
   Duration_MS_Mean: "40.8"
   Duration_MS_Min: "37.8"
   Duration_MS_Max: "107.4"
   Duration_MS_Last: "39.2"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 300
FocusLaplace:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "16.8"
   Duration_MS_Min: "15.1"
   Duration_MS_Max: "314.4"
   Duration_MS_Last: "16.5"
   kernel_size: 3
Canny:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "55.5"
   Duration_MS_Min: "50.3"
   Duration_MS_Max: "100.6"
   Duration_MS_Last: "54.4"
   threshold1: 65
   threshold2: 96
FileWriter:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
   writeCaptureStream: 0
