%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "7.76"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.8"
   Duration_MS_Min: "0.5"
   Duration_MS_Max: "654.7"
   Duration_MS_Last: "0.5"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "J:EMCAStitchingrid_1_1"
Simple:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "1.9"
   Duration_MS_Min: "1.6"
   Duration_MS_Max: "3.0"
   Duration_MS_Last: "1.9"
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "4.4"
   Duration_MS_Min: "4.0"
   Duration_MS_Max: "15.6"
   Duration_MS_Last: "4.9"
   use_Cuda: 0
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "26.5"
   Duration_MS_Min: "25.9"
   Duration_MS_Max: "37.1"
   Duration_MS_Last: "26.0"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 256
   omega: 50
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "4.8"
   Duration_MS_Min: "4.2"
   Duration_MS_Max: "6.2"
   Duration_MS_Last: "4.7"
   kernel_size: 3
FocusLaplace:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "6.1"
   Duration_MS_Min: "5.5"
   Duration_MS_Max: "421.7"
   Duration_MS_Last: "6.3"
   kernel_size: 3
Canny1:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Canny2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.1"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Cartoon1:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "27.3"
   Duration_MS_Min: "25.5"
   Duration_MS_Max: "29.3"
   Duration_MS_Last: "27.3"
   algorithm: 1
   r: 352
   s: 408
Cartoon2:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "27.2"
   Duration_MS_Min: "25.6"
   Duration_MS_Max: "28.9"
   Duration_MS_Last: "27.2"
   algorithm: 2
   r: 375
   s: 465
