%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "94.8"
   Duration_MS_Min: "1.5"
   Duration_MS_Max: "6961.3"
   Duration_MS_Last: "18.8"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: ""
Canny:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "3.3"
   Duration_MS_Min: "2.2"
   Duration_MS_Max: "142.9"
   Duration_MS_Last: "2.4"
