%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "122.2"
   Duration_MS_Min: "118.4"
   Duration_MS_Max: "600.6"
   Duration_MS_Last: "120.2"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 4507
   gain: 366
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "15.3"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "41.8"
   Duration_MS_Last: "15.7"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "24.2"
   Duration_MS_Min: "23.2"
   Duration_MS_Max: "120.4"
   Duration_MS_Last: "24.3"
   kernel_size: 3
   show_slider: 1
