%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "143.7"
   Duration_MS_Min: "137.1"
   Duration_MS_Max: "640.0"
   Duration_MS_Last: "142.1"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 2817
   gain: 0
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Average:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.6"
   Duration_MS_Min: "1.9"
   Duration_MS_Max: "6.4"
   Duration_MS_Last: "1.9"
   frames_to_average: 6
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "4.3"
   Duration_MS_Min: "1.9"
   Duration_MS_Max: "42.5"
   Duration_MS_Last: "13.8"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "7.7"
   Duration_MS_Min: "23.3"
   Duration_MS_Max: "30.7"
   Duration_MS_Last: "24.3"
   kernel_size: 3
   show_slider: 1
