%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: -1
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "21.8"
   Duration_MS_Min: "1.4"
   Duration_MS_Max: "62.7"
   Duration_MS_Last: "8.1"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: ""
Canny:
   IsEnabled: 1
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "2.6"
   Duration_MS_Min: "2.1"
   Duration_MS_Max: "69.5"
   Duration_MS_Last: "2.4"
