%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "114.4"
   Duration_MS_Min: "107.1"
   Duration_MS_Max: "566.6"
   Duration_MS_Last: "110.9"
   camera_index: 0
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 2895
   exposureSliderMax: 10000
   gain: 634
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
Average:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   frames_to_average: 4
BrightDark:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.0"
   Duration_MS_Min: "13.4"
   Duration_MS_Max: "38.1"
   Duration_MS_Last: "13.9"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "18.4"
   Duration_MS_Min: "18.1"
   Duration_MS_Max: "19.6"
   Duration_MS_Last: "18.3"
   kernel_size: 5
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 8
   Duration_MS_Mean: "39.5"
   Duration_MS_Min: "38.2"
   Duration_MS_Max: "45.4"
   Duration_MS_Last: "38.4"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 300
FocusLaplace:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "19.7"
   Duration_MS_Min: "16.1"
   Duration_MS_Max: "312.9"
   Duration_MS_Last: "16.1"
   kernel_size: 3
Canny:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "52.7"
   Duration_MS_Min: "52.1"
   Duration_MS_Max: "61.9"
   Duration_MS_Last: "53.4"
   threshold1: 100
   threshold2: 200
FileWriter:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
   writeCaptureStream: 0
