%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "138.0"
   Duration_MS_Min: "107.1"
   Duration_MS_Max: "562.8"
   Duration_MS_Last: "109.6"
   camera_index: 0
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 5479
   exposureSliderMax: 250000
   gain: 404
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 1
Average:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   frames_to_average: 4
BrightDark:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 5
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 8
   Duration_MS_Mean: "181.2"
   Duration_MS_Min: "170.5"
   Duration_MS_Max: "196.2"
   Duration_MS_Last: "171.6"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 1024
   omega: 300
FocusLaplace:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "34.8"
   Duration_MS_Min: "16.7"
   Duration_MS_Max: "304.7"
   Duration_MS_Last: "16.7"
   kernel_size: 3
Canny:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "54.5"
   Duration_MS_Min: "53.6"
   Duration_MS_Max: "62.9"
   Duration_MS_Last: "54.6"
   threshold1: 100
   threshold2: 200
FileWriter:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
