%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
CamXimea:
   LastDurationMS: "119.0"
   IsEnabled: 1
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 10000
   gain: 1000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
Canny:
   LastDurationMS: "60.0"
   IsEnabled: 1
Stats:
   LastDurationMS: "16.3"
   IsEnabled: 1
