%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 0
   CudaDeviceIndex: 0
CamXimea:
   camera_index: 0
   minimum_buffers: 1
   focus: 0.
   focalLength: 0.
   aperature: 0.
   focusMovementValue: 0.
   exposure: 117000.
   LastDurationMS: "81.3"
RunningStats:
   LastDurationMS: "477.7"
