%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 0
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.5"
   Duration_MS_Min: "1.3"
   Duration_MS_Max: "38.8"
   Duration_MS_Last: "24.7"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "J:EMCAStitchingrid_1_1"
Canny1:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.6"
   Duration_MS_Min: "2.1"
   Duration_MS_Max: "7.9"
   Duration_MS_Last: "2.5"
   threshold1: 100
   threshold2: 200
Canny2:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.5"
   Duration_MS_Min: "1.8"
   Duration_MS_Max: "6.5"
   Duration_MS_Last: "2.4"
   threshold1: 100
   threshold2: 200
