%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "15.34"
   CudaEnabledDeviceCount: -1
   CudaDeviceIndex: 1
   UseCuda: 0
CamDefault:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.2"
   Duration_MS_Min: "0.1"
   Duration_MS_Max: "0.2"
   Duration_MS_Last: "0.2"
   # Set camera_index to -1 to skip use of camera
   camera_index: 0
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "J:EMCAStitchingrid_1_1"
Simple:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "2.1"
   Duration_MS_Min: "1.7"
   Duration_MS_Max: "7.4"
   Duration_MS_Last: "1.9"
Stats:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "4.2"
   Duration_MS_Min: "3.3"
   Duration_MS_Max: "20.0"
   Duration_MS_Last: "3.7"
   use_Cuda: 0
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "22.5"
   Duration_MS_Min: "21.3"
   Duration_MS_Max: "36.5"
   Duration_MS_Last: "22.7"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 256
   omega: 50
FocusSobel:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   kernel_size: 3
FocusLaplace:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "11.3"
   Duration_MS_Min: "10.5"
   Duration_MS_Max: "16.7"
   Duration_MS_Last: "11.7"
   kernel_size: 3
Canny1:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "1.7"
   Duration_MS_Min: "1.5"
   Duration_MS_Max: "2.6"
   Duration_MS_Last: "1.6"
   threshold1: 100
   threshold2: 200
Canny2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 100
   threshold2: 200
Cartoon1:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   algorithm: 1
   r: 352
   s: 408
Cartoon2:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   algorithm: 2
   r: 375
   s: 465
