%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "3.37"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "97.0"
   Duration_MS_Min: "96.2"
   Duration_MS_Max: "98.2"
   Duration_MS_Last: "97.3"
   camera_index: 0
   trigger_software: 1
   minimum_buffers: 1
   aperture: 0
   minFocusMovementValue: 2
   exposure: 2901
   exposureSliderMax: 10000
   gain: 0
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 1
CapturePostProcessing:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "53.0"
   Duration_MS_Min: "40.6"
   Duration_MS_Max: "358.1"
   Duration_MS_Last: "41.2"
   correction_bright_dark: 1
   correction_upshift4bits: 1
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   downsample_preview_factor: 2
QC:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "10.0"
   Duration_MS_Min: "9.5"
   Duration_MS_Max: "11.2"
   Duration_MS_Last: "9.6"
Stats:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   use_Cuda: 1
FocusFFT:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 8
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "21.1"
   Duration_MS_Min: "20.8"
   Duration_MS_Max: "21.7"
   Duration_MS_Last: "21.5"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 256
   omega: 102
Canny:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 65
   threshold2: 96
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 1
   Duration_MS_Mean: "49.8"
   Duration_MS_Min: "48.1"
   Duration_MS_Max: "54.0"
   Duration_MS_Last: "49.9"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
