%YAML:1.0
GraphManager:
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "111.1"
   Duration_MS_Min: "104.8"
   Duration_MS_Max: "161.0"
   Duration_MS_Last: "113.9"
   camera_index: 0
   minimum_buffers: 1
   aperture: 1200
   minFocusMovementValue: 2
   exposure: 6211
   exposureSliderMax: 15000
   gain: 479
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
BrightDark:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "12.6"
   Duration_MS_Min: "12.2"
   Duration_MS_Max: "24.7"
   Duration_MS_Last: "12.4"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "13.5"
   Duration_MS_Min: "12.9"
   Duration_MS_Max: "41.0"
   Duration_MS_Last: "13.1"
   use_Cuda: 1
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ZoomViewLockIndex: -1
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   directory: "J:/junk"
   name: foo
   ext: ".tif"
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: g
