%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
CamXimea:
   camera_index: 0
   minimum_buffers: 1
   focus: 0.
   focalLength: 0.
   aperature: 0.
   focusMovementValue: 0.
   exposure: 124000.
   LastDurationMS: "82.6"
CudaHistogram:
   LastDurationMS: "33.6"
RunningStats:
   LastDurationMS: "519.5"
