%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: 2.0301967531564280e+000
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "317.3"
   Duration_MS_Min: "316.2"
   Duration_MS_Max: "327.0"
   Duration_MS_Last: "316.3"
   camera_index: 0
   minimum_buffers: 1
   aperture: 13576
   minFocusMovementValue: 2
   exposure: 200000
   exposureSliderMax: 200000
   gain: 2284
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 1
Average:
   IsEnabled: 0
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   frames_to_average: 4
BrightDark:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "11.2"
   Duration_MS_Min: "11.0"
   Duration_MS_Max: "13.4"
   Duration_MS_Last: "11.1"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "15.1"
   Duration_MS_Min: "13.1"
   Duration_MS_Max: "39.5"
   Duration_MS_Last: "13.2"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "17.5"
   Duration_MS_Min: "17.1"
   Duration_MS_Max: "19.6"
   Duration_MS_Last: "17.1"
   kernel_size: 7
FocusFFT:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 8
   Duration_MS_Mean: "39.3"
   Duration_MS_Min: "38.4"
   Duration_MS_Max: "42.0"
   Duration_MS_Last: "38.9"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 300
FocusLaplace:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "31.4"
   Duration_MS_Min: "16.1"
   Duration_MS_Max: "318.3"
   Duration_MS_Last: "16.1"
   kernel_size: 3
Canny:
   IsEnabled: 0
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "0.0"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "0.0"
   Duration_MS_Last: "0.0"
   threshold1: 65
   threshold2: 96
FileWriter:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "35.5"
   Duration_MS_Min: "34.2"
   Duration_MS_Max: "36.9"
   Duration_MS_Last: "35.9"
   directory: "J:/junk"
   baseFileName: test
   ext: ".tif"
   useSourceFileName: 0
   # Set writeOnKeyHit to a single char to trigger write if that key is hit. Leave empty to write every frame.
   writeOnKeyHit: ""
   # writeCaptureSteam == 1 : write Cap stream, == 0 : write Out stream.
   writeCaptureStream: 1
