%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "144.9"
   Duration_MS_Min: "136.7"
   Duration_MS_Max: "651.0"
   Duration_MS_Last: "139.7"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 2817
   gain: 0
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 0
   show_aperature_slider: 0
Average:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "2.5"
   Duration_MS_Min: "1.9"
   Duration_MS_Max: "15.6"
   Duration_MS_Last: "1.9"
   frames_to_average: 4
   show_slider: 1
Stats:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "3.4"
   Duration_MS_Min: "1.9"
   Duration_MS_Max: "38.7"
   Duration_MS_Last: "13.7"
   use_Cuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 2
   Duration_MS_Mean: "6.1"
   Duration_MS_Min: "23.5"
   Duration_MS_Max: "36.7"
   Duration_MS_Last: "24.4"
   kernel_size: 3
   show_slider: 1
Canny:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 5
   Duration_MS_Mean: "13.8"
   Duration_MS_Min: "54.8"
   Duration_MS_Max: "69.6"
   Duration_MS_Last: "55.9"
Simple:
   IsEnabled: 1
   ShowView: 1
   ZoomViewLockIndex: 5
   Duration_MS_Mean: "7.5"
   Duration_MS_Min: "29.8"
   Duration_MS_Max: "45.2"
   Duration_MS_Last: "30.2"
