%YAML:1.0
GraphManager:
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
CamXimea:
   IsEnabled: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "137.1"
   Duration_MS_Min: "120.9"
   Duration_MS_Max: "597.7"
   Duration_MS_Last: "135.4"
   camera_index: 0
   minimum_buffers: 1
   focus: 1
   focalLength: 0
   aperture: 1200
   focusMovementValue: 0.
   exposure: 3380
   gain: 4958
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
Stats:
   IsEnabled: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "15.8"
   Duration_MS_Min: "0.0"
   Duration_MS_Max: "42.2"
   Duration_MS_Last: "15.5"
   use_Cuda: 1
