%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "1.12"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "60.4"
   Duration_MS_Min: "58.8"
   Duration_MS_Max: "68.1"
   Duration_MS_Last: "61.7"
   camera_index: 0
   trigger_software: 0
   minimum_buffers: 1
   aperture: 1200
   minFocusMovementValue: 2
   exposure: 4000
   exposureSliderMax: 3000
   gain: 7465
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
CapturePostProcessing:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "119.1"
   Duration_MS_Min: "33.3"
   Duration_MS_Max: "8558.0"
   Duration_MS_Last: "33.8"
   correction_bright_dark: 1
   correction_upshift4bits: 1
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   overwrite_capture: 1
