%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "0.84"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
ImageQC:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "10.9"
   Duration_MS_Min: "10.1"
   Duration_MS_Max: "11.8"
   Duration_MS_Last: "11.8"
FocusFFT:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   UseCaptureCorrectedStream: 0
   Duration_MS_Mean: "52.2"
   Duration_MS_Min: "42.0"
   Duration_MS_Max: "58.1"
   Duration_MS_Last: "52.3"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 50
