%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: 2.3144803068400575e+000
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "19.5"
   Duration_MS_Min: "18.1"
   Duration_MS_Max: "20.7"
   Duration_MS_Last: "19.6"
   kernel_size: 3
FocusFFT:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "40.6"
   Duration_MS_Min: "38.2"
   Duration_MS_Max: "55.2"
   Duration_MS_Last: "38.3"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 50
ImageStatistics:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.1"
   Duration_MS_Min: "13.5"
   Duration_MS_Max: "39.1"
   Duration_MS_Last: "13.6"
   use_Cuda: 1
