%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: 2.5812229633178774e+000
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
FocusSobel:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "19.2"
   Duration_MS_Min: "17.9"
   Duration_MS_Max: "21.0"
   Duration_MS_Last: "20.8"
   kernel_size: 3
FocusFFT:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "43.3"
   Duration_MS_Min: "38.4"
   Duration_MS_Max: "57.9"
   Duration_MS_Last: "39.8"
   # Power of 2 (256, 512, 1024, 2048)
   dft_size: 512
   omega: 50
ImageStatistics:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "14.3"
   Duration_MS_Min: "13.5"
   Duration_MS_Max: "40.0"
   Duration_MS_Last: "13.6"
   use_Cuda: 1
