%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: 3.2004940886216713e+000
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "124.5"
   Duration_MS_Min: "123.5"
   Duration_MS_Max: "134.4"
   Duration_MS_Last: "123.8"
   camera_index: 0
   minimum_buffers: 1
   aperture: 1200
   minFocusMovementValue: 2
   exposure: 2755
   exposureSliderMax: 3000
   gain: 7465
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
BrightDark:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "11.4"
   Duration_MS_Min: "11.1"
   Duration_MS_Max: "14.0"
   Duration_MS_Last: "11.5"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
