%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "0.34"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
Delay:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "16.7"
   Duration_MS_Min: "12.3"
   Duration_MS_Max: "31.6"
   Duration_MS_Last: "17.5"
   delayMS: 10
