%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   FPS: "2.38"
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimeaDummy:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   InputStream: 0
   Duration_MS_Mean: "19.7"
   Duration_MS_Min: "18.1"
   Duration_MS_Max: "23.2"
   Duration_MS_Last: "19.7"
   # Set camera_index to -1 to skip use of camera
   camera_index: -2
   # .tiff, .png, or .jpg
   image_name: ""
   movie_name: ""
   image_dir: "./SampleImages"
