%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "108.8"
   Duration_MS_Min: "106.9"
   Duration_MS_Max: "114.9"
   Duration_MS_Last: "108.6"
   camera_index: 0
   minimum_buffers: 1
   aperture: 1200
   minFocusMovementValue: 2
   exposure: 10000
   exposureSliderMax: 260000
   gain: 1000
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
BrightDark:
   IsEnabled: 1
   ShowView: 0
   ShowViewControls: 0
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "11.7"
   Duration_MS_Min: "11.4"
   Duration_MS_Max: "13.7"
   Duration_MS_Last: "11.4"
   bright_field_path: "config/BrightField.tif"
   dark_field_path: "config/DarkField.tif"
   show_slider: 1
