%YAML:1.0
GraphManager:
   Enabled: 1
   # Log Levels: 0=trace, 1=debug, 2=info, 3=notice, 4=warn, 5=err, 6=critical, 7=alert, 8=emerg, 9=off
   LogLevel: 2
   CudaEnabledDeviceCount: 1
   CudaDeviceIndex: 1
   UseCuda: 1
CamXimea:
   IsEnabled: 1
   ShowView: 1
   ShowViewControls: 1
   ZoomViewLockIndex: 0
   Duration_MS_Mean: "179.3"
   Duration_MS_Min: "108.4"
   Duration_MS_Max: "1035.2"
   Duration_MS_Last: "118.9"
   camera_index: 0
   minimum_buffers: 1
   aperture: 1200
   minFocusMovementValue: 2
   exposure: 10000
   exposureSliderMax: 260000
   gain: 1000
   gainSliderMax: 10000
   show_gain_slider: 1
   show_exposure_slider: 1
   show_focus_slider: 1
   show_aperature_slider: 0
